# Target specific macros
TARGET = practica_2b_cliente
TARGET_SOURCES := \
	practica_2b_cliente.c
TOPPERS_OSEK_OIL_SOURCE := ./practica_2b_cliente.oil

O_PATH ?= build

include ../../../nxtOSEK/ecrobot/ecrobot.mak
