# Target specific macros
TARGET = practica_2b_servidor
TARGET_SOURCES := \
	practica_2b_servidor.c
TOPPERS_OSEK_OIL_SOURCE := ./practica_2b_servidor.oil

O_PATH ?= build

include ../../../nxtOSEK/ecrobot/ecrobot.mak
